/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "tzlxgvrgkkzsmbvsoxef"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6bHhndnJna2t6c21idnNveGVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzExMjE4NzgsImV4cCI6MjA4NjY5Nzg3OH0.hGcQVZ1_MMb8z75GUiNFYZa-spsWCdjR4ystS0PZY8g"
